app/models/battle.py
from app.models import battle_db


class Battle:
    
    def __init__(self, player_pokemon_data, enemy_trainer, enemy_pokemon_data, player_health, enemy_health, player_moves, enemy_moves, log=None, turn=1):
        self.turn = turn
        self.enemy_trainer = enemy_trainer
        self.player_pokemon_data = player_pokemon_data
        self.enemy_pokemon_data = enemy_pokemon_data
        if log is None:
            self.log=[]
        else:
            self.log=log
        self.player_health = player_health
        self.enemy_health = enemy_health
        self.player_moves = player_moves
        self.enemy_moves = enemy_moves

app/routes/battle_routes.py
from datetime import datetime
import random
from flask import Blueprint, redirect, render_template, request, session, url_for
from app.models.battle import Battle
from app.decorators import required_login
from app.models.battle_db import Battle_db
from app.models.trainer import Trainer
from app.repositories.battle_repo import create_battle
from app.repositories.trainer_repo import add_exp, add_lose, add_win, get_random_trainer, get_trainer_by_id
from app.services.battle_services import apply_damage, calculateDamage, getLife, getMove, get_battle_result
from app.services.pokemon_services import obtain_pokemon_by_name

battle_bp = Blueprint('battle', __name__, template_folder='templates')

current_year = datetime.now().year


@battle_bp.route('/')
@required_login
def battles():

    if not session.get("pokemon_selected") or not session.get("pokemon_enemy_name"):
        session.pop("battle", None)
        session.pop("pokemon_selected", None)
        session.pop("pokemon_enemy_name", None)
        session.pop("pokemon_player_moves", None)
        session.pop("pokemon_enemy_moves", None)
        page = 1
        return redirect(url_for("pokemon.pokedex", page=page))

    pokemon_player_name = session.get('pokemon_selected')
    pokemon_enemy_name_str = session.get("pokemon_enemy_name")
    pokemon_player_moves = session.get("pokemon_player_moves")
    pokemon_enemy_moves = session.get("pokemon_enemy_moves")
    enemy_trainer = get_random_trainer(session.get("trainer")["name"]).name

    if session.get("battle"):
        battle_temp = session.get("battle")
        if battle_temp.get("player_pokemon_data", {}).get("name") != pokemon_player_name:
            session.pop("battle", None)

    if session.get("battle") is None:
        pokemon_player = obtain_pokemon_by_name(pokemon_player_name)
        pokemon_enemy = obtain_pokemon_by_name(pokemon_enemy_name_str)

        battle = Battle(pokemon_player, enemy_trainer, pokemon_enemy, getLife(pokemon_player), getLife(
            pokemon_enemy), pokemon_player_moves, pokemon_enemy_moves)
        session["battle"] = battle.__dict__
    else:
        battle_data = session.get("battle")
        battle = Battle(**battle_data)
        pokemon_player = battle.player_pokemon_data
        pokemon_enemy = battle.enemy_pokemon_data

    return render_template("battles.html", battle=battle, pokemon=pokemon_player, pokemon_enemy=pokemon_enemy, music=url_for('static', filename='sounds/inicio.mp3'), current_year=current_year)


@battle_bp.route('/attack', methods=['GET', 'POST'])
@required_login
def attack():
    if request.method == "GET":
        if session["battle"]:
            return redirect(url_for("battle.battles"))
        else:
            return redirect(url_for("pokemon.pokedex", page=1))
    elif request.method == "POST":
        if not session.get("battle"):
            return redirect(url_for("battle.battleResult"))

        move_name = request.form.get("move")
        battle_data = session.get("battle")
        battle = Battle(**battle_data)
        player = battle.player_pokemon_data
        enemy = battle.enemy_pokemon_data

        player_move = getMove(player, move_name)
        player_damage, player_log = calculateDamage(player, enemy, player_move)
        battle.enemy_health, enemy_ko = apply_damage(
            battle.enemy_health, player_damage)
        battle.log.append(player_log)

        if enemy_ko:
            battle.log.append(
                f"{enemy['name']} died and {player['name']} wins!")
            session["battle"] = battle.__dict__
            return redirect(url_for("battle.battleResult"))

        enemy_moves_list = session.get("pokemon_enemy_moves")
        enemy_move = random.choice(enemy_moves_list)
        enemy_damage, enemy_log = calculateDamage(enemy, player, enemy_move)
        battle.player_health, player_ko = apply_damage(
            battle.player_health, enemy_damage)
        battle.log.append(enemy_log)

        if player_ko:
            battle.log.append(
                f"{player['name']} died and {enemy['name']} wins!")
            session["battle"] = battle.__dict__
            return redirect(url_for("battle.battleResult"))

        session["battle"] = battle.__dict__
        return redirect(url_for("battle.battles"))


@battle_bp.route('/result')
@required_login
def battleResult():
    if not session.get("battle"):
        return redirect(url_for("pokemon.pokedex", page=1))

    battle_data = session.get("battle")
    battle = Battle(**battle_data)
    winner, loser = get_battle_result(battle)

    trainer_dict = session.get("trainer")
    trainer_id = trainer_dict["id"]
    trainer = get_trainer_by_id(trainer_id)

    i_win = False
    if winner == session.get('pokemon_selected'):
        i_win = True
        add_win(trainer)
        session["trainer"]["wins"] += 1
        add_exp(trainer, 100)
        session["trainer"]["exp"] += 100
    else:
        add_lose(trainer)
        session["trainer"]["loses"] += 1
        add_exp(trainer, 30)
        session["trainer"]["exp"] += 30

    winnerTrainer = None
    loserTrainer = None
    if i_win:
        winnerTrainer = session.get("trainer")["name"]
        loserTrainer = battle.enemy_trainer
    else:
        winnerTrainer = battle.enemy_trainer
        loserTrainer = session.get("trainer")["name"]

    trainer1 = session.get("trainer")["name"]
    trainer2 = battle.enemy_trainer
    pokemon1 = battle.player_pokemon_data
    pokemon2 = battle.enemy_pokemon_data

    battle_db = Battle_db(trainer_1=trainer1, trainer_2=trainer2, pokemon_1=pokemon1["name"],
                          pokemon_2=pokemon2["name"], winner=winnerTrainer, loser=loserTrainer)
    
    create_battle(battle_db, trainer_id)
    
 

    return render_template("battle_result.html", battle=battle, winner=winner, loser=loser, i_win=i_win)


@battle_bp.route("/rematch")
@required_login
def rematch():
    if not session.get("battle"):
        return redirect(url_for("pokemon.pokedex", page=1))

    battle_data = session.get("battle")
    battle = Battle(**battle_data)

    battle.player_health = getLife(battle.player_pokemon_data)
    battle.enemy_health = getLife(battle.enemy_pokemon_data)
    battle.log = []

    session["battle"] = battle.__dict__

    return redirect(url_for("battle.battles"))

app/routes/home_routes.py
from datetime import datetime
from flask import Blueprint, redirect, render_template, request, session, url_for
from app.models.exceptions import TrainerNotFound
from app.models.trainer import Trainer
from app.repositories.battle_repo import delete_battle, get_battle_by_id, get_battles_by_trainer
from app.repositories.trainer_repo import add_trainer, get_trainer_by_name
from app.services.auth_services import authenticate

home_bp = Blueprint('home', __name__, template_folder='templates')

current_year = datetime.now().year


@home_bp.route('/', methods=["GET", "POST"])
def index():
    error = None
    if request.method == "GET":
        session.clear()
    elif request.method == "POST":
        nameIntroduced = request.form.get("trainer").lower()
        passwordIntroduced = request.form.get("password")

        if nameIntroduced is None or passwordIntroduced is None:
            error = "Name and password required"
        else:
            try:
                trainer = authenticate(nameIntroduced, passwordIntroduced)
                session["trainer"] = trainer.to_dict()
                page = 1
                return redirect(url_for("pokemon.pokedex", page=page))
            except TrainerNotFound:
                error = "Incorrect username or password"

    return render_template('index.html', error=error, current_year=current_year, music=url_for('static', filename='sounds/inicio.mp3'))


@home_bp.route('/sign-up', methods=["GET", "POST"])
def sign_up():
    error = None
    name = None
    password1 = None
    password2 = None

    if request.method == "GET":
        return render_template('sign-up.html', current_year=current_year, music=url_for('static', filename='sounds/inicio.mp3'))

    if request.method == "POST":
        name = request.form.get("name").lower()
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        if not name or not password1 or not password2:
            error = "All fields are required"
        elif len(name) < 3 or len(name) > 15:
            error = "The username must have a minimum of 3 characters and a maximum of 15."
        elif len(password1) <= 3 or len(password2) <= 3:
            error = "The password must have a minimum 4 characters"
        elif password1 != password2:
            error = "The passwords are not the same"
        elif get_trainer_by_name(name):
            error = "This trainer already exists"

        if error:
            return render_template('sign-up.html', error=error, music=url_for('static', filename='sounds/inicio.mp3'))
        elif error is None:
            session["trainer_name"] = name
            session["trainer_password"] = password2
            # add_trainer(name, password2)
            return redirect(url_for("home.trainer_skin"))


@home_bp.route('/profile-skin', methods=["GET", "POST"])
def trainer_skin():
    name = session.get("trainer_name", None)
    password = session.get("trainer_password", None)
    selected_skin = "trainer3"
    if request.method == "GET":
        selected_skin = request.args.get("skin", None)
        session["selected_skin"] = selected_skin

    if request.method == "POST":
        selected_skin = session.get("selected_skin", "trainer3")
        action = request.form.get("action", None)
        if action == "save_and_sign_up":
            add_trainer(name, password, selected_skin)
            return render_template("index.html", success="Trainer created successfully! You can log in now.", current_year=current_year)
        if action == "go_back":
            return redirect(url_for("home.sign_up"))

    return render_template("skin_selection.html", current_year=current_year, selected_skin=selected_skin, music=url_for('static', filename='sounds/inicio.mp3'))


@home_bp.route('/Profile')
def profile():
    trainer1 = session.get("trainer")["name"]
    battles = get_battles_by_trainer(trainer1)
    return render_template('profile.html', current_year=current_year, battles=battles, music=url_for('static', filename='sounds/inicio.mp3'))

@home_bp.route('/battle-details/<int:battle_id>')
def battle_details(battle_id):
    if "trainer" not in session:
        return redirect(url_for('home.index'))
        
    battle = get_battle_by_id(battle_id)

    return render_template('battle_details.html', battle=battle, current_year=current_year, music=url_for('static', filename='sounds/inicio.mp3'))

@home_bp.route('/battle/delete/<int:battle_id>', methods=["POST"])
def delete_battle_action(battle_id):
    if "trainer" not in session:
        return redirect(url_for('home.index'))
    
    battle = get_battle_by_id(battle_id)
    if not battle:
        return redirect(url_for('home.profile'))

    current_user_name = session["trainer"]["name"] #esto comprueba que para eliminar la batalla la haya tenido que iniciar el primero
    
    if battle.trainer_1 != current_user_name:
        return redirect(url_for('home.profile'))
    
    delete_battle(battle_id)
    
    return redirect(url_for('home.profile'))

@home_bp.route('/log-out')
def log_out():
    session.clear()
    return redirect(url_for('home.index'))


@home_bp.route('/404')
def error404():
    return render_template('404.html', current_year=current_year, music=url_for('static', filename='sounds/inicio.mp3')), 404

app/routes/pokemon_routes.py
from datetime import datetime
import random
from flask import Blueprint, redirect, render_template, request, session, url_for
from app.models.trainer import Trainer
from app.repositories.trainer_repo import get_random_trainer, get_trainer_by_id
from app.services import pokemon_services
from app.decorators import required_login


pokemon_bp = Blueprint('pokemon', __name__, template_folder='templates')

current_year = datetime.now().year


@pokemon_bp.route('')
@required_login
def pokedex():
    session.pop("battle", None)
    session.pop("pokemon_selected", None)
    session.pop("pokemon_enemy_name", None)
    session.pop("pokemon_player_moves", None)
    session.pop("pokemon_enemy_moves", None)

    page = request.args.get('page', 1, type=int)
    session["page"] = page

    if (page > 169):
        return redirect(url_for("home.error404"))
    elif (page < 1):
        return redirect(url_for("home.error404"))

    pokemon_list = pokemon_services.list_pokemons(page)
    error_message = session.get("error_message", None)
    return render_template('pokedex.html',  pokemon_list=pokemon_list, music=url_for('static', filename='sounds/inicio.mp3'), current_year=current_year, error_message=error_message, page=page)


@pokemon_bp.route("/<int:pokemon_id>")
@required_login
def pokemon_details(pokemon_id):
    pokemon = pokemon_services.obtain_pokemon_by_id(pokemon_id)
    page = session.get("page")
    if pokemon is None:
        return redirect(url_for("home.error404"))
    else:
        return render_template("pokemon_details.html", page=page, music=url_for('static', filename='sounds/inicio.mp3'), pokemon=pokemon, current_year=current_year)


@pokemon_bp.route('/pokemon_selected', methods=["POST"])
@required_login
def pokemon_selected():
    pokemon_name_input = request.form.get('search').lower()
    page = session.get("page")

    session["pokemon_selected"] = pokemon_name_input
    pokemonEncontrado = pokemon_services.obtain_pokemon_by_name(
        session["pokemon_selected"])

    if pokemonEncontrado:
        all_moves_player = pokemonEncontrado["moves"]
        if len(all_moves_player) < 4:
            session["pokemon_player_moves"] = all_moves_player
        else:
            session["pokemon_player_moves"] = random.sample(
                all_moves_player, 4)

        random_enemy_id = random.randint(1, 151)
        pokemon_enemy_object = pokemon_services.obtain_pokemon_by_id(
            random_enemy_id)

        session["pokemon_enemy_name"] = pokemon_enemy_object["name"]
        all_moves_enemy = pokemon_enemy_object["moves"]

        if len(all_moves_enemy) < 4:
            session["pokemon_enemy_moves"] = all_moves_enemy
        else:
            session["pokemon_enemy_moves"] = random.sample(all_moves_enemy, 4)

        return redirect(url_for('battle.battles'))
    else:
        session["error_message"] = "Pokemon not found enter the name correctly"
        return redirect(url_for("pokemon.pokedex", page=page))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/favicon" href="{{url_for('static', filename='images/index-page/logo.png')}}" alt="Logo">
    <title>{% block title %}My Site{%endblock%}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/base.css')}}"
    />
    {%block styles%} {%endblock%}
  </head>

  <body>
    <header>{%block header%}{%endblock%}</header>
    <main>
      <button id="muteBtn">🔇</button>
      <audio id="backgroundMusic" autoplay loop></audio>
      {%block content%} {%endblock%}
    </main>

    <footer class="footer-container">
      <p>
        &copy; {{current_year}} PokeCode. All rights reserved by Izan Álvarez
        and Axel Cartaya
      </p>
    </footer>
    
    <script src="{{ url_for('static', filename='js/enter.js') }}"></script>
    <script>
      const musicSrc = "{{ music }}";
    </script>
    <script src="{{ url_for('static', filename='js/music.js') }}"></script>
  </body>
</html>

app/templates/battle_details.html
{% extends "base.html" %} {% block title %}Battle #{{ battle.id }}{% endblock %}
{% block styles %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/battle-detail.css')}}"
/>
{% endblock %} {% block header %}
<div class="back-button-container">
  <a href="{{url_for('home.profile')}}">
    <img
      src="{{url_for('static', filename='images/pokemon_details-page/flecha.png')}}"
      alt="Back"
    />
  </a>
</div>
{% endblock %} {% block content %}
<div class="high-container">
  <div class="container">
    <div class="battle-header">
      <h1>Battle Report #{{ battle.id }}</h1>
      <p class="date-info">{{ battle.date.strftime('%d-%m-%Y %H:%M') }}</p>
    </div>

    <div class="matchup-container">
      <div class="contender">
        <span class="trainer-name">{{ battle.trainer_1 }}</span>
        <span class="pokemon-used">{{ battle.pokemon_1 }}</span>
      </div>

      <div class="vs-sign">VS</div>

      <div class="contender">
        <span class="trainer-name">{{ battle.trainer_2 }}</span>
        <span class="pokemon-used">{{ battle.pokemon_2 }}</span>
      </div>
    </div>

    <div class="result-box">
      <h2>WINNER</h2>
      <div class="winner-text">{{ battle.winner.capitalize() }}</div>

      <hr style="border: 1px dashed black; width: 50%; margin: 15px auto" />

      <h3>Loser</h3>
      <div class="loser-text">{{ battle.loser.capitalize() }}</div>
    </div>

    {% if session.trainer.name == battle.trainer_1 %}
    <form
      action="{{ url_for('home.delete_battle_action', battle_id=battle.id) }}"
      method="post"
      style="margin-top: 20px"
    >
      <button type="submit" class="delete-btn">DELETE BATTLE</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/battle_result.html
{%extends "base.html"%} {%block title%}Battle Results{%endblock%} {%block
styles%}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/battle_result.css')}}"
/>
{%endblock%} {% block content %}
<div class="result-container">
  <div>
    <h1>Battle over!{{ " You won!" if i_win else " You lost!" }}</h1>
    <h2>Winner: {{ winner }}</h2>
    <h3>Looser: {{ loser }}</h3>
  </div>
  <div class="log">
    <h3>Combat summary:</h3>
    <ul>
      {% for entry in battle.log %}
      <li>{{ entry }}</li>
      {% endfor %}
    </ul>
  </div>
  <p id="exp-gained">
    You gained {{ 100 if i_win else 30 }} experience points!
  </p>
  <div class="button-container">
    <a id="rematch-btn" href="{{ url_for('battle.rematch') }}" class="btn"
      >Play again</a
    >
    <a
      id="return-btn"
      href="{{ url_for('pokemon.pokedex', page=1) }}"
      class="btn"
      >Return to the Pokédex</a
    >
  </div>
</div>
{%endblock%}

app/templates/battles.html
{%extends "base.html" %} {%block title%}Battle{%endblock%} {%block styles%}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/battles.css')}}"
/>
{%endblock%} {%block content%}
<div class="screen-container">
  <div class="grid-container">
    <div class="log-container">
      {% if battle.log %}
      <div class="battle-log">
        <h3>Battle log:</h3>
        <ul>
          {% for entry in battle.log %}
          <li>{{ entry }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </div>

    <div class="moves-container">
      <form method="POST" action="{{ url_for('battle.attack') }}">
        <div class="moves-grid">
          {% for move in session.pokemon_player_moves %}
          <button
            type="submit"
            name="move"
            value="{{ move['name'] }}"
            class="move-button {{ move['type'] }}"
          >
            <span class="move-name">{{ move['name'] | title }}</span>
            <div class="move-details">
              <span class="m-power">Power: {{ move['power'] }}</span>
              <span class="m-type-tag {{ move['type'] }}"
                >Type: {{ move['type'] }}</span
              >
            </div>
          </button>
          {% endfor %}
        </div>
      </form>
    </div>

    <div
      class="pokemon1-container {% if pokemon["name"]=='pikachu' %} pikachu{% endif %}"
    >
      <div class="name-hp-container">
        <p class="name">{{pokemon["name"]}}</p>
        <div class="health">
          <p class="hp">HP:</p>
          {% set max_hp = pokemon["stats"][0]['value'] %} {% set cur_hp =
          battle.player_health %} {% if max_hp > 0 %} {% set pct = (cur_hp /
          max_hp) * 100 %} {% else %} {% set pct = 0 %} {% endif %}
          <span class="hp-text">{{ cur_hp }}/{{ max_hp }}</span>
          <div class="health-bar-wrapper">
            <div
              class="health-bar {% if pct >= 50 %}hp-high{% elif pct >= 20 %}hp-medium{% else %}hp-low{% endif %}"
              role="progressbar"
              aria-valuenow="{{ cur_hp }}"
              aria-valuemax="{{ max_hp }}"
              style="width: {{ pct|round(0, 'floor') }}%;"
            ></div>
          </div>
        </div>
      </div>
      <div class="img-container">
        <img src="{{pokemon["sprites"]["back_default"]}}" alt="" />
      </div>
    </div>

    <div
      class="pokemon2-container {% if pokemon_enemy["name"]=='pikachu' %} pikachu {% endif %}"
    >
      <div class="name-hp-container">
        <p class="name">{{pokemon_enemy["name"] }}</p>
        <div class="health">
          <p class="hp">HP:</p>
          {% set max_hp_e = pokemon_enemy["stats"][0]['value'] %} {% set cur_hp_e =
          battle.enemy_health %} {% if max_hp_e > 0 %} {% set pct_e = (cur_hp_e
          / max_hp_e) * 100 %} {% else %} {% set pct_e = 0 %} {% endif %}
          <span class="hp-text">{{ cur_hp_e }}/{{ max_hp_e }}</span>
          <div class="health-bar-wrapper">
            <div
              class="health-bar {% if pct_e >= 50 %}hp-high{% elif pct_e >= 20 %}hp-medium{% else %}hp-low{% endif %}"
              role="progressbar"
              aria-valuenow="{{ cur_hp_e }}"
              aria-valuemax="{{ max_hp_e }}"
              style="width: {{ pct_e|round(0, 'floor') }}%;"
            ></div>
          </div>
        </div>
      </div>
      <div class="img-container">
        <img src="{{pokemon_enemy["sprites"]["front_default"]}}" alt="" />
      </div>
    </div>
  </div>
</div>
{%endblock%}

app/templates/pokedex.html
{% extends "base.html" %} {% block title%}Pokedex{%endblock%} {%block styles%}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/pokedex.css')}}"
/>
{%endblock%} {%block header%}
<div class="header-container">
  <a href="{{url_for('home.index')}}">
    <img
      src="{{url_for('static', filename='images/index-page/logo1.webp')}}"
      alt="PokeCode logo"
    />
  </a>
  <!-- <a href="{{url_for('home.log_out')}}" id="log-out">LOG OUT</a> -->
  <nav class="menu-navegacion">
    <button class="boton-menu trainer">{{session.trainer.name}} ▼</button>
    <div class="contenido-desplegable">
      <a href="{{url_for('home.profile')}}">PROFILE</a>
      <a href="{{url_for('home.log_out')}}" id="log-out">LOG OUT</a>
    </div>
  </nav>
</div>
{%endblock%} {%block content%}
<div class="flex">
  <div class="welcome-container">
    <p
      id="text"
      data-text="Pokedex loaded! Let’s explore some Pokémon info!"
    ></p>
  </div>
  <form action="{{url_for('pokemon.pokemon_selected')}}" method="post">
    <input
      type="text"
      name="search"
      id="search"
      placeholder="Pick your Pokémon"
    />
    <button type="submit" class="enter-button">Start</button>
  </form>
</div>
{% if error_message%}
<p id="error">{{error_message}}</p>
{% endif %} 
<div class="card_container">
  {% for pokemon in pokemon_list %}
  <a href="{{url_for('pokemon.pokemon_details', pokemon_id=pokemon.id)}}">
    <div class="pokemon_container">
      <div class="img_container">
        <img src="{{pokemon["sprites"]["front_default"]}}" />
      </div>
      <div class="id_name_container">
        <p class="id">#{{pokemon["id"]}}</p>
        <p class="name">{{pokemon["name"]}}</p>
      </div>
      <div class="types">
        {% for tipo in pokemon["types"]%}
        <p class="type {{ tipo }}">{{tipo}}</p>
        {%endfor%}
      </div>
    </div>
  </a>
  {% endfor %}
</div> 
<div class="contenedor-btns">
{% if page > 1 %}
    <a href="{{ url_for('pokemon.pokedex', page=page-1) }}" class="btnPaginacion"> 
       Anterior 
    </a>
  {% endif %}
{% if page < 169 %}
  <a href="{{ url_for('pokemon.pokedex', page=page+1) }}" class="btnPaginacion"> 
      Siguiente
  </a>
  {% endif %}
</div>
{%endblock%}

app/templates/profile.html
{% extends "base.html" %} {% block title%}Profile:
{{session.trainer.name}}{%endblock%} {%block styles%}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/profile.css')}}"
/>
{%endblock%} {%block header%}

<div class="back-button-container">
  <a href="{{url_for('pokemon.pokedex', page=1)}}">
    <img
      src="{{url_for('static', filename='images/pokemon_details-page/flecha.png')}}"
      alt=""
    />
  </a>
</div>

{%endblock%} {%block content%}
<a href="{{url_for('home.log_out')}}" id="log-out">LOG OUT</a>
<div class="high-container">
  <div class="container">
    <div class="img-container">
      <img
        id="triner-img"
        src="{{url_for('static', filename='images/profile-page/trainers/' + session.trainer.skin + '.png')}}"
        alt="trainer"
      />
    </div>
    <p class="name">Trainer: {{session.trainer.name.capitalize() }}</p>
  </div>

  <div class="container">
    <h1>STATS</h1>
    <div class="stat-container">
      <div class="victorys">
        <span>Victorys:</span>
        <span>{{session.trainer.wins}}</span>
      </div>
      <div class="loses">
        <span>Loses:</span>
        <span>{{session.trainer.loses}}</span>
      </div>
      <div class="games">
        <span>Games:</span>
        <span>{{session.trainer.wins+session.trainer.loses}}</span>
      </div>
      <div class="win-rate">
        <span>Win rate:</span>
        <span
          >{% if session.trainer.wins+session.trainer.loses == 0 %} 0% {% else
          %} {{ '%.2f' % (session.trainer.wins * 100 / (session.trainer.wins +
          session.trainer.loses)) }}% {% endif %}
        </span>
      </div>
    </div>
    <div class="lvl">
      <span id="exp">EXP: {{ session.trainer.exp % 400 }}/400</span>
      <span id="level"
        >LVL: {{(session.trainer.exp/400) | round(0, method='floor') |
        int}}</span
      >
    </div>
  </div>

  <div class="container">
    <h1>History of Battles</h1>

    <div class="battles-list-container">
      {% for battle in battles %}
      <a
        href="{{ url_for('home.battle_details', battle_id=battle.id) }}"
        class="battle"
      >
        <div class="battle-info-row battle-vs">
          <p>{{battle.id}}</p>
          {{ battle.trainer_1 }} VS {{ battle.trainer_2 }}
        </div>

        <div class="battle-info-row">
          <span>Winner: {{ battle.winner }}</span>
        </div>
      </a>

      {% endfor %}
    </div>
  </div>
</div>
{%endblock%}